openfoodfacts/open-prices

- CONTRIBUTING.md
- INSTALL.md
- README.md
- app/api.py
- app/templates/index.html
Improve setup documentation : 
- update README.md
- create an INSTALL.md
- create a CONTRIBUTING.md
- add `pre-commit` to the dependencies
> docs: improve setup documentation

- .env
- .env.example
- .gitignore
- INSTALL.md
- README.md
- app/api.py
- app/config.py
- app/db.py
- requirements.txt
- install the `psycopg2-binary` & `sqlalchemy` dependencies. Remove `peewee`
- update the .env & app config to pass the postgres db config parameters
- connect to the db on app startup
- update documentation
TODO
- docker config ?
> build: add postgresql db config (with sqlalchemy)

- README.md
- doc: document the Weekly meeting
> docs: document the Weekly meeting

- app/crud.py
- app/tasks.py
- app/utils.py
following #45, we want to enrich the newly created Product with data fetched from OpenFoodFacts.
We use [openfoodfacts-python](https://github.com/openfoodfacts/openfoodfacts-python)
> feat: fetch product data from OpenFoodFacts

- app/api.py
- app/config.py
We need to allow users to fetch images they uploaded.
Two other fixes are included in the PR.
> feat: Add image serving

- app/models.py
- tests/test_api.py
- add field validation tests on `Price.labels_tags` & `Price.location_osm_type`
- fix 201 instead of 200
- ensure that tests run on the sqlite db (thanks to https://github.com/sqlalchemy/sqlalchemy/discussions/9530)
> build: improve tests

- app/templates/index.html
- underline all links
- fix a few sentences (minor edits)
> fix: improve landing page

- .github/workflows/release-please.yml
a personal access token is necessary to trigger Github actions
> fix: fix release please

- app/crud.py
Manage `image/webp` proof uploads.
`mimetype.guess_extension` returns None when a webp image is uploaded, so we need to make a special rule
> feat: manage webp proof uploads

- app/schemas.py
New filters on `product_id`, `location_id` & `owner`
> feat: add extra filters on GET /prices

- static/index.html
Add button link to the app (/app/)
> chore: improve landing page

- app/api.py
- tests/test_api.py
New endpoint `/products/code/<code>`
- similar to the Open Food Facts url scheme : https://world.openfoodfacts.org/product/8001505005707
- will be useful for https://github.com/openfoodfacts/open-prices-frontend/issues/38
> feat: add endpoint to retrieve product by code

- app/api.py
- tests/test_api.py
New endpoint `/locations/osm/<osm_type>/<osm_id>`
- similar to the OpenStreetMap url scheme : https://www.openstreetmap.org/node/6482573185
- will be useful for https://github.com/openfoodfacts/open-prices-frontend/issues/59
> feat: add endpoint to retrieve location by osm data

- app/api.py
- app/schemas.py
- tests/unit/test_schema.py
we were performing time-consuming model validation on trusted input.
> fix: improve price fetch performance

- app/schemas.py
New filters on `Product` model's `price_count` field
> feat: add product filter on price_count

- app/api.py
- app/crud.py
- app/models.py
- app/schemas.py
- tests/test_api.py
Similar to #26 & #122
New `/locations` endpoint to get / filter / sort the list of locations
Add tests
> feat: locations GET endpoint

- app/schemas.py
Following #140 
New filters on `Location` model's `price_count` field
> feat: add location filter on price_count

- app/api.py
- app/crud.py
- app/schemas.py
- app/tasks.py
- app/utils.py
- tests/test_api.py
- rename *Base to *Full
- new UserCreate to differentiate with UserBase
> refactor: rename schemas to clarify

- app/api.py
- app/crud.py
- app/schemas.py
- tests/test_api.py
Similar to #26, #122 & #138
New `/users` endpoint to get / filter / sort the list of users
Add tests
> feat: users GET endpoint

- docs/add-a-price.md
Update the existing doc : 
- the order of steps have changed
- "single price" to differentiate with "multiple prices"
> docs: update tutorial to add a price

- app/utils.py
Fix Sentry issue https://openfoodfacts.sentry.io/issues/4844456645/?project=4506270533091328&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
> fix: fix AttributeError in fetch_product_openfoodfacts_details

- docs/add-a-price.md
- static/fr/index.html
- static/index.html
> docs(tutorial): fix OpenStreetMap name

- INSTALL.md
Fix https://github.com/openfoodfacts/open-prices-frontend/issues/225
> docs: Welcome users

- app/api.py
- app/crud.py
To be called when the user logs out
> feat: add an endpoint to delete a session

- app/api.py
- app/auth.py
> fix: use opsession instead of session as cookie name

- app/schemas.py
Following #185
New filters on `Proof` model's `price_count` field
> feat: add proof filter on price_count

- app/api.py
- app/crud.py
- app/schemas.py
- app/tasks.py
- tests/test_api.py
New endpoint `/prices/{price_id}` to allow a user to delete one of it's price
The user must be authenticated + the price id must exist + the user must be the owner of the price
Also update `price_count` fields
> feat: new DELETE prices endpoint

- app/schemas.py
Add `proof_id` to `PriceFilter`
Closes #218
> feat: allow filtering Prices by proof_id

- app/api.py
- app/crud.py
- app/schemas.py
- tests/integration/test_api.py
Following #181 
The tests were breaking, and some changes were required
- use `PATCH` instead of `PUT`
- better manage unset & extra fields 
https://fastapi.tiangolo.com/tutorial/body-updates/#partial-updates-with-patch
> fix: fix price update endpoint

- app/routers/auth.py
- app/routers/locations.py
- app/routers/prices.py
- app/routers/products.py
- app/routers/proofs.py
- app/routers/users.py
Following #226
I had added trailing slashes `/`, but it was a mistake
https://github.com/tiangolo/fastapi/discussions/9328
> fix: remove trailing slash in API endpoints

- app/routers/prices.py
- tests/integration/test_api.py
In a particular case, the price transformation method was failing.
Fixed + added some tests to avoid it happening.
> fix(prices): improve private proof filtering depending on user

- app/crud.py
- app/schemas.py
Temporary solution to filter on the `categories_tags` field (field added in #192)
Temporary ? see discussion in the corresponding issue : #217
> feat(products): new filter by categories_tags

- app/crud.py
- app/schemas.py
Temporary solution to filter on the `labels_tags` field (similar to #234 ; field added in #208)
Temporary ? see discussion in this issue : #217
> feat(products): new filter by labels_tags

- app/crud.py
Implemented in #238
Went to fast, typo...
> fix(products): fix filter by labels_tags

- app/routers/prices.py
- app/routers/proofs.py
- tests/integration/test_api.py
A moderator should be able to edit a price he/she doesn't own
- add the check in the price patch endpoint
- add tests
- related cleanup (proof patch)
> feat(prices): allow moderators to edit prices

- app/auth.py
- app/crud.py
- app/models.py
- app/routers/prices.py
- app/routers/proofs.py
- app/schemas.py
- tests/integration/test_api.py
We don't want to store private proofs
> fix(proof): remove is_public flag

- app/utils.py
> fix: fix KeyError: 'unique_scans_n' error

- .github/workflows/quality-check.yml
we were pulling the docker image with tag dev, that does not exist
> ci: try to fix test CI

- app/scheduler.py
> fix: import dumps at 3PM instead of 10AM

- app/crud.py
- app/routers/locations.py
- app/schemas.py
- app/tasks.py
- tests/integration/test_api.py
- new `POST` `/api/v1/locations` to create a location. requires authentication
- added tests
- some refactoring
If it is a new location, then it returns 201.
But if the location already exist, then it returns the existing object (with a 200).
> feat(locations): add POST endpoint to create a location

- app/crud.py
- app/schemas.py
- tests/integration/test_api.py
New `Price` filter by `date__year` & `date__month`
Custom solution because not possible natively with `fastapi-filter` : created an issue https://github.com/arthurio/fastapi-filter/issues/592
(similar to #234)
> feat(prices): new date filter by year & month

- config/settings.py
- config/urls.py
- open_prices/api/auth/urls.py
- open_prices/api/auth/views.py
- open_prices/api/urls.py
- open_prices/api/views.py
- open_prices/common/authentication.py
- open_prices/common/openfoodfacts.py
- open_prices/users/models.py
- open_prices/users/utils.py
- poetry.lock
- pyproject.toml
Auth & session endpoints
Authentication helper (Authorization header or Cookie)
Breaking change : 
- the login endpoint is now `/auth/login` (instead of `/auth`)
Not used, maybe in the future ? https://django-oauth-toolkit.readthedocs.io/en/latest/index.html
> feat(Django): authentication via API

- config/settings.py
- open_prices/api/urls.py
- open_prices/api/users/filters.py
- open_prices/api/users/serializers.py
- open_prices/api/users/tests.py
- open_prices/api/users/views.py
- open_prices/users/factories.py
- open_prices/users/models.py
- poetry.lock
- pyproject.toml
`/api/v1/users` endpoint (with ordering & filtering)
> fea(Django): API Users endpoint

- open_prices/api/locations/serializers.py
- open_prices/api/locations/views.py
- open_prices/api/prices/serializers.py
- open_prices/api/products/serializers.py
- open_prices/api/products/views.py
- open_prices/api/proofs/filters.py
- open_prices/api/proofs/serializers.py
- open_prices/api/proofs/views.py
- open_prices/api/urls.py
- open_prices/proofs/models.py
- open_prices/proofs/utils.py
```
// restricted to the authenticated user proofs
/api/v1/proofs
/api/v1/proofs/id (GET, PATCH, DELETE)
/api/v1/proofs/upload (POST)
```
> feat(Django): API: Proof endpoints

- open_prices/api/prices/serializers.py
- open_prices/api/prices/views.py
- open_prices/prices/models.py
```
/api/v1/prices/<id> PATCH
/api/v1/prices/<id> DELETE
```
> feat(Django): API: Price PATCH & DELETE endpoints

- config/settings.py
- open_prices/api/auth/views.py
- open_prices/api/locations/tests.py
- open_prices/api/prices/tests.py
- open_prices/common/openfoodfacts.py
- open_prices/common/openstreetmap.py
- open_prices/locations/factories.py
- open_prices/locations/models.py
- open_prices/prices/models.py
- open_prices/prices/tests.py
- open_prices/products/factories.py
- open_prices/products/models.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
- on Price create, create/link Product & Location
- on Proof create, create/link Location
- on Product create, fetch data from OFF
- on Location create, fetch data from OSM
> feat(Django): fetch Product & Location data from external APIs (OFF, OSM)

- open_prices/common/tasks.py
- open_prices/common/utils.py
> feat(Django): daily DB backup task

- open_prices/common/openstreetmap.py
- open_prices/common/tests.py
- open_prices/common/utils.py
- open_prices/locations/models.py
- open_prices/locations/tasks.py
- open_prices/locations/tests.py
- open_prices/products/models.py
- open_prices/products/tasks.py
Following #373 & #376
We can now use `django-q2` to fetch data from OSM & OFF asynchronously
> refactor(Django): fetch data from OSM & OFF async

- app/crud.py
- app/schemas.py
Similar to #234 & #238
Temporary solution to filter on the `brands_tags` field
Temporary ? see discussion in the corresponding issue : #217
> feat(products): new filter by brands_tags

- open_prices/api/locations/tests.py
- open_prices/api/locations/views.py
- open_prices/api/prices/tests.py
- open_prices/api/prices/views.py
- open_prices/api/products/filters.py
- open_prices/api/products/tests.py
- open_prices/api/products/views.py
- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
- open_prices/api/users/tests.py
- open_prices/api/users/views.py
> fix(Django): extra API fixes

- open_prices/prices/models.py
- open_prices/prices/tests.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
Following discussions + adding new validation rules in https://github.com/openfoodfacts/open-prices/discussions/319
- improve validation on `Price.proof`
- add validation on `Price.date`
- add validation on `Proof.date`
> refactor(Django): extra Price & Proof field validations

- config/settings.py
- open_prices/api/locations/tests.py
- open_prices/api/prices/tests.py
- open_prices/api/proofs/tests.py
- open_prices/locations/models.py
- open_prices/prices/tests.py
- open_prices/products/models.py
- open_prices/proofs/tests.py
When running tests, avoid calling OFF & OSM APIs :)
> refactor(tests): skip Product & Location post_save signals

- open_prices/api/prices/serializers.py
- open_prices/api/prices/tests.py
- open_prices/api/prices/views.py
- open_prices/api/views.py
New `/prices/stats` endpoint.
Returns : price__count, price__min, price__max, price__avg
> feat(prices): new stats endpoint

- .github/labeler.yml
> ci: Autolabel some PRs

- open_prices/api/auth/views.py
- open_prices/common/openfoodfacts.py
- open_prices/users/utils.py
We already had the ` User.is_moderator`  field, but it was not user/updated depending on OFF auth
> refactor(users): update is_moderator on login

- config/settings.py
- open_prices/common/tasks.py
- open_prices/users/models.py
Following #440, #441 & #442
Add a weekly CRON that updates every user count field (price, location, product, proof)
> refactor(users): New weekly CRON to update User counts

- open_prices/common/tasks.py
- open_prices/common/utils.py
Following #380, the script wasn't actually working
> fix(Django): fix daily DB backup task

- open_prices/common/tasks.py
- open_prices/locations/models.py
Following #468, #470 & #471
Similar to #458
Add a weekly CRON that updates every location count field (price, user, product, proof)
> refactor(locations): New weekly CRON to update Location counts

- open_prices/api/stats/serializers.py
- open_prices/api/stats/tests.py
- open_prices/api/stats/views.py
- open_prices/api/urls.py
- open_prices/stats/models.py
Following #475
New `/api/v1/stats` that returns the `TotalStats` object
> feat(API): new /stats endpoint for TotalStats

- open_prices/api/stats/views.py
- open_prices/stats/admin.py
- open_prices/stats/migrations/0001_initial.py
- open_prices/stats/models.py
- open_prices/stats/tests.py
Following #475 , add the new `TotalStats` model to the admin (readonly)
> refactor(stats): add to admin, cleanup

- open_prices/common/tasks.py
- open_prices/products/models.py
Following #489, #490 & #491
Similar to #458 & #473
Add a weekly CRON that updates every product count field (price, user, location, proof)
> refactor(products): New weekly CRON to update Product counts

- open_prices/api/users/tests.py
- open_prices/api/users/views.py
Create a new User API endpoint: /users/:user_id
Only the authenticated user can query this detail endpoint
> feat(Users): new /users/:user_id endpoint. Only for self

- scripts/stats/top_products.py
Example script to get the number of top products with at least 1 price
Also created a wiki page : https://github.com/openfoodfacts/open-prices/wiki/Stats
> docs(Stats): simple script for top product stats (via API)

- open_prices/common/openfoodfacts.py
> fix(Product sync): Avoid setting None for missing fields. Use model default values instead

- .github/workflows/container-deploy.yml
- config/settings.py
- docker-compose.yml
- open_prices/api/proofs/serializers.py
- open_prices/api/proofs/views.py
- open_prices/common/gemini.py
- poetry.lock
- pyproject.toml
- Added a new endpoint `POST /api/v1/proofs/process_with_gemini`
- This requires a new .env variable `GOOGLE_GEMINI_API_KEY`
- Also adds a new dependency `google-generativeai`
- The endpoint accepts a list of `files` that it sends to gemini with a parsing prompt
- Files should be images of labels
- The reply from gemini is sent directly to the frontend. It contains a list of objects, one for each file, check the `gemini.py` file for a list of expected values for `origin`, `product` and `unit` fields.
```
{
"labels": [
{
"barcode": "3235223055203",
"organic": false,
"origin": "unknown",
"price": 3.85,
"product": "en:cherry-tomatoes",
"unit": "KILOGRAM"
},
{
"barcode": "335430001032",
"organic": false,
"origin": "unknown",
"price": 2.19,
"product": "en:strawberries",
"unit": "KILOGRAM"
}
] …
```
> feat(proofs): New endpoint to extract price data from images (with Gemini)

- nginx.conf
> chore: add CORS headers to data

- open_prices/locations/admin.py
- open_prices/prices/admin.py
- open_prices/proofs/admin.py
> refactor(Admin): add Price view. improve Location & Proof views.

- .env
- .github/workflows/container-deploy.yml
- .gitignore
- config/settings.py
- docker-compose.yml
Admin interface didn't work because CSRF was not configured properly.
> fix: fix CSRF configuration

- open_prices/proofs/management/commands/run_ocr.py
The OCR script was also processing thumbnails.
> fix: fix run_ocr.py script

- .env
- .github/workflows/container-deploy.yml
- .github/workflows/quality-check.yml
- Makefile
- docker-compose.yml
- docker/prod.yml
Add the necessary configuration for Open Prices to listen to the Redis stream.
> chore: enable fetching product updates from Redis

- open_prices/proofs/management/commands/run_ml_model.py
- open_prices/proofs/ml.py
- open_prices/proofs/tests.py
> fix: fix script that runs ML models for proofs without predictions

- Makefile
- open_prices/api/proofs/serializers.py
- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
- open_prices/proofs/ml.py
- Update price tag prediction after a user updates a price tag
- create a price tag prediction after a user manually creates a price tag
- return price tag predictions when listing/retrieving price tags
> feat: improve gemini processing

- open_prices/proofs/management/commands/run_ml_model.py
- open_prices/proofs/ml.py
- fix: process the most recent proofs first in run_ml_model CLI command
- fix: limit Gemini payload by resizing image (if needed) before upload
> fix: Improve gemini processing

- open_prices/api/prices/tests.py
- open_prices/prices/models.py
Allow API PATCH for Price category_tag, labels_tags & origins_tags fields
> feat(Prices): API: allow editing category-related fields

- open_prices/api/users/tests.py
- open_prices/api/users/views.py
Remove an existing rule where it was not possible to query user detail data
> refactor(Users): allow anyone to query any user

- open_prices/api/locations/serializers.py
- open_prices/api/locations/tests.py
- open_prices/api/prices/serializers.py
- open_prices/api/prices/tests.py
- open_prices/api/proofs/serializers.py
- open_prices/api/proofs/tests.py
- Proofs: return `source` info
- Prices: return `source` info
- Locations: return `source` info
> refactor(API): return proof/price/location source field

- open_prices/common/google.py
- open_prices/proofs/ml.py
Move some config from `/proofs/ml.py` to a dedicated `common/google.py` file
> refactor(Proofs): ML: move some config to a dedicated google.py file

- scripts/gdpr/README.md
- scripts/gdpr/create_prices_from_gdpr_csv.py
- scripts/gdpr/gdpr_field_mapping.csv
Some of the changes:
- Auchan quantity field
- Carrefour rules
- better manage files without EAN
- improve the docs
> refactor(GDPR): Improve script (fixes for Carrefour, Auchan)

- open_prices/common/tasks.py
- open_prices/moderation/rules.py
- open_prices/moderation/tests.py
Following #700
New rule: cleanup products with invalid barcodes (check digit), and their related prices.
IF AND ONLY IF they come from the price validation web workflows.
see https://github.com/openfoodfacts/open-prices/discussions/319
> feat(Moderation): script to remove Products (and their prices) with invalid barcodes

- open_prices/api/proofs/filters.py
- open_prices/api/proofs/tests.py
- open_prices/common/constants.py
Following #773 & #774
allow filtering proofs by kind: COMMUNITY or CONSUMPTION
> feat(Proofs): API: new filter on `kind`

- .github/workflows/release-please.yml
Reverts openfoodfacts/open-prices#757
> Revert "build(deps): bump GoogleCloudPlatform/release-please-action from 3.7.13 to 4.2.0"

- open_prices/proofs/management/commands/match_price_tags_with_existing_prices.py
- open_prices/proofs/management/commands/match_receipt_items_with_existing_prices.py
- open_prices/proofs/tests.py
- open_prices/proofs/utils.py
Similar to #650 (`PriceTag`), but for `ReceiptItem` (new model added in #778)
Reusable command
> feat(Receipt Item): script to match historical ReceiptItem with their prices

- open_prices/challenges/models.py
- open_prices/prices/models.py
- open_prices/prices/tests.py
- new Price `in_challenge` queryset
- new Challenge `start_date_with_time` & `end_date_with_time` properties
- add tests
> refactor(Challenges): new Price queryset to filter on the ones part of a challenge

- open_prices/prices/models.py
- open_prices/prices/tests.py
Following #808
New `Price.in_challenge(<challenge>)` method
> refactor(Challenges): new Price property to check if it belongs in a given challenge

- open_prices/api/challenges/serializers.py
- open_prices/api/challenges/tests.py
- open_prices/challenges/models.py
> feat(Challenges): new tag property. return in the API

- open_prices/prices/models.py
- open_prices/prices/tests.py
Following #807
- new `Price.objects.has_tag(<tag:str>)` queryset
- add a test
> refactor(Prices): new has_tag queryset

- open_prices/challenges/models.py
- open_prices/challenges/tests.py
- open_prices/prices/models.py
- open_prices/prices/tasks.py
Helper method to easily find and update all the Challenge's prices (set their tag)
> refactor(Challenges): new set_price_tags helper method

- open_prices/challenges/models.py
- open_prices/challenges/tests.py
- open_prices/proofs/models.py
Similar to #815
Helper method to easily find and update all the Challenge's proofs (set their tag)
> refactor(Challenges): new set_proof_tags helper method

- README.md
> docs: design promo

- mkdocs.yml
> ci: Add edit button to doc

- open_prices/challenges/tests.py
- open_prices/prices/models.py
- open_prices/prices/tests.py
Following #819
- Category prices are not included in challenges stats, even when their category matches.
> fix(Prices): also look at category_tag for in_challenge checks

- open_prices/locations/models.py
- open_prices/proofs/management/commands/match_price_tags_with_existing_prices.py
- open_prices/proofs/management/commands/match_receipt_items_with_existing_prices.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
Following #650 & #788
Use annotates to filter and loop only on usable proofs
> refactor(Proofs): improve PriceTag & ReceiptItem matching script performance

- open_prices/proofs/factories.py
- open_prices/proofs/ml.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
Following #834 (new `PriceTag.tags` field)
Linked to #688
- method to set a tag depending on "rules"
- signal to automatically run the method on PriceTagPrediction creation
> feat(Price Tag): predictions: helper methods to know if the detected data is "valid"

- open_prices/common/openfoodfacts.py
- open_prices/common/tests.py
- open_prices/moderation/rules.py
- open_prices/proofs/models.py
- scripts/shop_import/create_prices_from_csv.py
Wrap the `openfoodfacts.barcodehas_valid_check_digit()` method inside our own method
To add a check if the barcode is numeric or not.
> refactor(OpenFoodFacts): create a dedicated barcode_is_valid method

- open_prices/api/prices/filters.py
- fixes https://github.com/openfoodfacts/open-prices/issues/796
> feat(API): Prices: Add filter on location__osm_name__contains & product_name

- open_prices/products/management/commands/run_update_listener.py
The update was failing for Open Beauty Facts.
> fix: fix bug in Redis update listener

- open_prices/api/auth/views.py
> fix: we should return but not raise Response

- Makefile
See https://openfoodfacts.slack.com/archives/C032PK9D8/p1751647721480569 for more information
> fix: fix livecheck command

- open_prices/proofs/models.py
- open_prices/proofs/tests.py
- open_prices/proofs/utils.py
Following a new schema in #885
We need to update the matching script logic for category_tag
> refactor(Price Tags): predictions: update the matching script logic following changes in the schema

- open_prices/proofs/management/commands/run_ml_models.py
It leaves a bit of time if the proof is currently processed, and prevent duplicated predictions.
> fix: don't process proofs that were just uploaded

- open_prices/proofs/management/commands/run_ml_models.py
- open_prices/proofs/ml.py
- The `run_ml_models`  always run `receipt_extraction`: we now add an option to be able to explicitely add it (or not)
- The `run_ml_models` was running `price_tag_extraction` even if it was not in `types`
- fix a serialization bug in `extract_from_receipt`
- don't crash in `create_receipt_items_from_proof_prediction` if the prediction is empty (`price_prediction.data == {}`)
> fix: fix proof extraction script and extract_from_receipt function

- open_prices/proofs/admin.py
add ProofPrediction & subsequent models to the admin view
> refactor(Proofs): add admin integration for prediction models

- open_prices/prices/management/commands/remove_duplicates.py
- open_prices/proofs/management/commands/remove_duplicate_proofs.py
- Improve documentation and make the remove_duplicate_proofs more robust (see https://github.com/openfoodfacts/open-prices/pull/902)
- Improve robustness and comments after review in https://github.com/openfoodfacts/open-prices/pull/900
> fix: improve cleanup scripts

- open_prices/proofs/ml.py
- open_prices/proofs/utils.py
> refactor(Proofs): move cropping logic to utils

- .github/workflows/container-deploy.yml
> chore: use `europe-west1` location

- open_prices/proofs/management/commands/remove_duplicate_proofs.py
This improves the `remove_duplicate_proofs` script so that prices associated to proof to delete are associated with reference proof instead.
> fix: associate prices to ref proof (remove_duplicate_proofs)

- open_prices/api/products/views.py
> fix(API): Products: order by ID by default instead of `created`

- open_prices/locations/models.py
- open_prices/prices/models.py
- open_prices/products/models.py
- open_prices/proofs/models.py
- open_prices/users/models.py
Linked to #355 (rewrite the app in Django)
> chore(Django): cleanup remaining comments regarding DB mgmt

- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
> fix: return HTTP 201 when uploading duplicate proof on Smooth app

- open_prices/common/tasks.py
> fix(Challenges): forgot to call the update stats task every night

- open_prices/challenges/models.py
- open_prices/challenges/tests.py
Following https://github.com/openfoodfacts/open-prices/pull/941
> refactor(Challenges): new price_count & price_from_user_proof_count ranking stats

- open_prices/challenges/models.py
- open_prices/challenges/tests.py
Following https://github.com/openfoodfacts/open-prices/pull/941
Similar to #989 & #991 (other rankings)
> refactor(Challenges): new location price count rankings (location id, city & country)

- open_prices/challenges/models.py
- open_prices/challenges/tests.py
Similar to #995 (locations) but for products
> refactor(Challenges): new product price count ranking

- open_prices/challenges/models.py
- open_prices/challenges/tests.py
- set_tags: queryset optimizations on the Challenge methods added in https://github.com/openfoodfacts/open-prices/pull/810 & https://github.com/openfoodfacts/open-prices/pull/819
- reset_tags helper method
> refactor(Challenges): improve set_tags methods. new reset_tags methods

- open_prices/api/locations/tests.py
- open_prices/api/locations/views.py
- open_prices/api/proofs/views.py
Similar to #983
Following #554 where we return the existing location if we detect a duplicate
> refactor(Locations): return "detail": "duplicate" when a duplicate location is created

- poetry.lock
- pyproject.toml
Following https://github.com/openfoodfacts/openfoodfacts-python/pull/390
Needed for #1012
> build(deps): update openfoodfacts-python to 3.1.0

- open_prices/api/products/views.py
Following #1012 (APIs to create product & image in OFF)
Fix the image upload to actually select the image as front in OFF
> refactor(Products): Automatically set the uploaded image as the selected front (english)
