openfoodfacts/open-prices

- .env
- app/api.py
- app/config.py
- app/crud.py
- app/schemas.py
- requirements.txt
- new POST endpoint `/auth`
- check that users exist via https://world.openfoodfacts.org/cgi/auth.pl
- on success, generate a token and store in the the `User` db
- return the token
> feat: authentication workflow and store user token

- app/api.py
- app/crud.py
- new `GET` endpoint `/prices`
- no authentication needed
- basic filters
- look at `fastapi-filter` for additional/complex filtering
- and `fastapi-pagination`
> feat: prices GET endpoint

- app/api.py
- app/crud.py
- app/schemas.py
- poetry.lock
- pyproject.toml
- install [fastapi-filter](https://github.com/arthurio/fastapi-filter)
- setup advanced filtering on GET /prices endpoint
> feat: add advanced filtering on GET /prices

- app/api.py
- pyproject.toml
Similar to the FastAPI docs, create a `get_db()` method, and add it as a Depend in the corresponding endpoints.
Avoids having `global db`
https://fastapi.tiangolo.com/tutorial/sql-databases/#main-fastapi-app
> fix: stop using global db, use get_db instead

- app/api.py
- app/crud.py
- tests/test_api.py
- new endpoint `GET /locations/id` to get location details
- also return `location_id` in price endpoints
- add tests
> feat: GET /locations/id endpoint to get location details

- app/api.py
- app/crud.py
- tests/test_api.py
- new endpoint `GET /products/id` to get product details
- add tests
> feat: GET /products/id endpoint to get product details

- .github/workflows/container-deploy.yml
- Makefile
Everything to know is in the title ;)
> chore: migrate before deployment

- INSTALL.md
- remove mentions of venv & requirements.txt
- document poetry install for non-docker setup
> docs: replace mentions to venv with poetry

- app/schemas.py
- inherit `ProductBase` from `ProductCreate` (avoids duplicating the `code` field)
- add description to all Product fields
> feat: improve Product schema (inherit, field description)

- alembic/versions/20231123_0828_5acb37b190cc_add_prices_category_tag_field.py
run `pre-commit run --all-files` and fix the migration file that was making the CI fail
> build: fix CI (linting of migration file)

- .gitignore
- tests/test_api.py
Mostly on field validation: currency, product_code, category_tag
> feat: additional tests on Price create

- .env
- .github/workflows/container-deploy.yml
- app/api.py
- app/config.py
- docker-compose.yml
https://fastapi.tiangolo.com/tutorial/cors/
- add cors configuration in `app.py`
- update `.env`
- update docker config
> feat: add CORS configuration

- app/api.py
- app/auth.py
By providing `set_cookie=1`, the API sets an auth cookie on the device.
> feat: add support for cookie authentication

- app/api.py
The default return was a 200.
But we create objects (POST /prices & POST /proofs) so we should return a 201.
> fix: return 201 instead of 200 on price (& proof) create

- app/crud.py
- app/enums.py
- app/models.py
- app/schemas.py
Improve the `Price.currency` field
- stop using the `sqlachemy_utils CurrencyType`
- use instead a simple Enum generate from babel
- all the possible values are now visible in the schema
> feat: simply Price.currency validation

- app/schemas.py
providing `labels_tags` didn't work, because the validator was broken.
> fix: fix labels_tags field validator

- .gitignore
- app/api.py
- app/config.py
- app/schemas.py
- docker-compose.yml
- docker/dev.yml
- nginx.conf
- static/index.html
- static/robots.txt
- tests/test_api.py
The front-end (the content in the dist folder) must be deployed under /static/app
- use an nginx server as a reverse-proxy
- serve static assets (images, robots.txt, index.html) through nginx
- host OpenAPI docs under /api/docs (instead of /docs)
> feat: add frontend app

- app/api.py
https://fastapi.tiangolo.com/tutorial/metadata/
To better group endpoints
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices/assets/7147385/a51ca79a-599f-49d6-a3af-5428d6f194ee)|![image](https://github.com/openfoodfacts/open-prices/assets/7147385/28066739-3109-47ed-bba8-5f8f26e9146f)|
> feat: add openapi tags on endpoints

- app/api.py
- app/crud.py
- app/schemas.py
- tests/test_api.py
Enrich `price` objects with `product` & `location` objects.
Return `null` if no data.
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices/assets/7147385/ce89dccf-abdc-422e-a198-8e61c3f1d4de)|![Screenshot from 2023-12-18 15-48-49](https://github.com/openfoodfacts/open-prices/assets/7147385/61e32637-99f2-41a3-8cff-af2afcd549bd)|
> feat: add relationship objects in response of GET /prices

- app/crud.py
- app/schemas.py
- tests/test_api.py
Following #29
https://fastapi-filter.netlify.app/#order-by
New `order_by` parameter.
Add tests
> feat: add sorting on GET /prices

- app/api.py
- app/crud.py
- app/schemas.py
- tests/test_api.py
Currently we create proofs without defining their type.
With this PR the `type` info is now mandatory to create a proof.
> feat: ask for proof type when creating

- README.md
- doc: I've looked too many times for the frontend URL
> docs: add a link to the frontend repo

- app/schemas.py
- tests/test_api.py
New price filters on raw product fields : 
- `category_tags`
- `labels_tags__like` (array)
- `origins_tags__like` (array)
Add tests
> feat: add price filters on category_tag, labels_tags & origins_tags

- app/api.py
- app/crud.py
- app/schemas.py
- tests/test_api.py
Similar to #26 
New endpoint to get / filter / sort on `products`
Add tests
> feat: products GET endpoint

- app/api.py
- app/crud.py
- tests/test_api.py
Currently on each new login, we would delete any existing user and recreate it + generate a new token.
But it had some big limitations : 
- lose created info
- regenerate a token, so it would not be possible to have a fixed token on multiple devices
Changed to creating a new user only if it doesn't already exist
> feat(auth): avoid recreating existing user on login

- app/api.py
- app/crud.py
- app/schemas.py
- tests/test_api.py
Improve the current GET `/proofs` endpoint with : 
- pagination
- filter on `type` (reminder: also a default filter on `owner` as the authenticated user)
- sort
Add tests
> feat: paginate, filter & order proofs

- app/api.py
- app/schemas.py
- fix: don't use email as userid. Users can possibly authenticate using emails, fetch the userid from the /cgi/auth.pl response from Product Opener
- chore: add /api/v1/session endpoint to get info about current session
> fix: fix email sign-in

- .github/workflows/quality-check.yml
- Dockerfile
- Makefile
- app/crud.py
- app/schemas.py
- docker-compose.yml
- docker/dev.yml
- tests/integration/test_api.py
This way, we can test against PostgreSQL database. In the commit, we also:
- removed labels_tags__like and origins_tags__like filters. These filters triggers an error in PostgreSQL, as we're using a JSONB field type, which does not support LIKE queries (this bug was in production too, see https://openfoodfacts.sentry.io/issues/4911496304/?project=4506270533091328&query=LIKE&referrer=issue-stream&sort=freq&statsPeriod=90d&stream_index=0)
- fixed some integration tests to make it work with PostgreSQL
> ci: run integration tests and unit tests in docker. remove sqlite

- nginx.conf
Enable gzip encoding to improve web app performance.
Inspired by [these findings](https://github.com/openfoodfacts/open-prices-frontend/issues/88#issuecomment-1941359326).
> perf: enable gzip encoding

- nginx.conf
Enable cache for static files in nginx.
Add max possible age for them as files built by `vite` have a hash and will be invalidated after each change
> perf: enable cache for static files in nginx

- app/api.py
A single user was registered in DB against 2 different username due to lack of lowercasing.
A manual fix in DB should be done in production after deployment.
> fix: lowercase the user_id

- static/es/index.html
- static/fr/index.html
- static/index.html
A new translation of the landing page: neutral spanish
missing spanish translation of the landing page
index static html
> feat: translate landing page in spanish

- docker-compose.yml
nginx container did not restart during the VM reboot, because the restart policy was lacking.
> chore: fix restart policy for nginx

- app/crud.py
- app/routers/prices.py
- app/routers/proofs.py
- app/schemas.py
- tests/integration/test_api.py
- Added a PATCH /api/v1/proofs/{id} endpoint to allow update of boolean `is_public` and to change `type`
- `is_public` can only be set to `False` at creation/upload. Now user can correct this afterwards.
- Added `type` as patchable. In the frontend, a proof  `type` is automatically set depending on the "Add Price" mode selected. In the future, proof creation and price addition will be decoupled and a page dedicated to proof(s) upload in frontend should come soon. User might not set the right `type`.
Closes #236
> feat: add PATCH endpoint to update proof

- app/crud.py
- app/schemas.py
- app/tasks.py
- tests/integration/test_api.py
Locations tests are commented because they fail.
`LocationCreate` used to create fixtures is not a complete object so some fields are empty in the DB when using the paginate query. By using `LocationFull` we create a full entry in the DB (with an `osm_name`) that can be queried.
> fix: use LocationFull for fixtures

- app/schemas.py
In the `PriceCreate` schema, some examples were missing, and some were incorrect.
They are useful for API users to understand the expected format : https://prices.openfoodfacts.org/api/docs#/Prices/create_price_api_v1_prices_post
> docs: improve examples of Price schema

- app/tasks.py
Products first entered in Open Prices were not updated once added in OFF. Their "source" is set to None/null.
- if user enters a product with barcode that is not a food product but has the same barcode as a food product (is that possible?)
- #243
> fix(products): update products added first in Open Prices

- app/crud.py
- app/schemas.py
- app/tasks.py
- tests/integration/test_api.py
Similar to #240
Product filter tests are commented because they fail.
`ProductCreate` used to create fixtures is not a complete object so some fields are empty in the DB when using the paginate query. By using `ProductFull` we create a full entry in the DB that can be queried.
> fix(tests): use ProductFull for fixtures

- app/tasks.py
Following #256, linked to issue #243
Tentative fix the Product sync with OFF, to better manage border cases : 
- products added first in OP, then in OFF
- a Product should be updated depending on its `source_last_synced` field, not his `updated` field (the product can be updated in OP regardless, for example incrementing its `price_count`)
Reset all product source fields to `None`
> fix(sync): tentative fix of Product sync with OFF

- app/routers/prices.py
- tests/integration/test_api.py
Issue #182
A moderator should be able to delete a price he/she doesn't own
- add the check in the price delete endpoint
- add tests
> feat(prices): allow moderators to delete prices

- tests/integration/test_api.py
Add extra tests on price create endpoint : 
- with decimal as comma (error)
- with long decimal (truncates to 2)
> refactor: add tests on price create with decimal

- app/config.py
- app/scheduler.py
- app/tasks.py
- static/es/index.html
- static/fr/index.html
- static/index.html
Dump every night prices, locations and proofs, and store them in gzipped JSONL files under /data.
Also update the landing page to mention these dumps.
> feat: add daily dumps of DB main tables as JSONL files

- .github/workflows/release-please.yml
- https://github.com/google-github-actions/release-please-action is deprecated and replaced by https://github.com/googleapis/release-please-action
- Warning: Unexpected input(s) 'changelog-types', valid inputs are ['token', 'release-type', 'path', 'target-branch', 'config-file', 'manifest-file', 'repo-url', 'github-api-url', 'github-graphql-url', 'fork', 'include-component-in-tag', 'proxy-server', 'skip-github-release', 'skip-github-pull-request', 'changelog-host']
> ci: update release please config

- app/crud.py
- app/routers/prices.py
- app/schemas.py
- tests/integration/test_api.py
- tests/unit/test_schema.py
Currently we don't have any validation on `PriceBasicUpdatableFields`, so a user could add a negative price...
Related to this comment : https://github.com/openfoodfacts/openfoodfacts-dart/issues/942#issuecomment-2193797666
- new `PriceBase` schema
- renamed `PriceBasicUpdatableFields` to `PriceUpdate`
- made all fields of `PriceUpdate` optional (for the PATCH method)
- added their WithValidation counterparts, to validation on creation/update, but skip on get (to speed up !)
It still doesn't validate the edition of the `price_per` field, because it relies on fields (`product_code`, `category_tags`) that are not available in the `PriceBase` schema... :thinking: 
- https://stackoverflow.com/a/76560886/4293684
- https://fastapi.tiangolo.com/tutorial/body-updates/
- …
> refactor(prices): reorganise schema inheritance to validate price updates

- app/crud.py
- app/routers/prices.py
- app/routers/proofs.py
- app/schemas.py
- tests/integration/test_api.py
- tests/unit/test_schema.py
Similar to #342
- new `ProofBase` schema
- renamed `ProofBasicUpdatableFields` to `ProofUpdate`
- made all fields of `ProofUpdate` optional (for the PATCH method)
- inherited `ProofUpdate` from `ProofBase` to have field validation (though no validation yet on the schema)
- inherited `ProofCreate` from `ProofBase`
> refactor(proofs): reorganise schema inheritance

- .github/workflows/release-please.yml
Following #333 the issue with PRs not appearing in the release-please PRs seem to be related with the config, and the version.
I reverted to the same config as the frontend repo : https://github.com/openfoodfacts/open-prices-frontend/blob/master/.github/workflows/release-please.yml
> ci: revert release-please config to v3

- docker-compose.yml
to prevent docker overlay due to ~/.cache
> chore: add home_cache volume

- open_prices/api/locations/filters.py
- open_prices/api/locations/serializers.py
- open_prices/api/locations/tests.py
- open_prices/api/locations/views.py
- open_prices/api/prices/filters.py
- open_prices/api/prices/serializers.py
- open_prices/api/prices/tests.py
- open_prices/api/prices/views.py
- open_prices/api/products/filters.py
- open_prices/api/products/serializers.py
- open_prices/api/products/tests.py
- open_prices/api/products/views.py
- open_prices/api/urls.py
- open_prices/api/users/tests.py
- open_prices/locations/factories.py
- open_prices/prices/factories.py
- open_prices/products/factories.py
```
/api/v1/locations
/api/v1/locations/id
/api/v1/locations/osm/{osm_type}/{osm_id}
/api/v1/products
/api/v1/products/id
/api/v1/products/code/{code}
/api/v1/prices
```
> feat(Django): API: Location, Product & Price GET endpoints

- config/settings.py
- open_prices/common/openfoodfacts.py
- open_prices/common/tasks.py
- poetry.lock
- pyproject.toml
Installed `django-q2`
```
poetry add django-q2 blessed croniter
```
- with 2 extra packages
- using the DB as message broker
- why this package ? See #355 for a comparison
Create scheduled task (how to create automatically ?)
```
from django_q.models import Schedule
Schedule.objects.create(func="open_prices.common.openfoodfacts.import_product_db_full", schedule_type=Schedule.CRON, cron="0 15 * * *")
```
Sync product flavor manually
```
// python manage.py shell_plus
import openfoodfacts
from open_prices.common import openfoodfacts as common_openfoodfacts
common_openfoodfacts.import_product_db(flavor=openfoodfacts.Flavor.opf)
```
> feat(Django): daily sync of products from OFF

- open_prices/api/prices/serializers.py
- open_prices/api/prices/tests.py
- open_prices/api/prices/views.py
- open_prices/locations/factories.py
- open_prices/prices/models.py
- open_prices/prices/tests.py
- open_prices/products/factories.py
- open_prices/proofs/factories.py
On Price create
- increment Proof.price_count
- increment Location.price_count
- increment Product.price_count
On Price delete
- decrement Proof.price_count
- decrement Location.price_count
- decrement Product.price_count
> feat(Django): update price_counts on Price create/delete

- config/settings.py
- open_prices/api/auth/serializers.py
- open_prices/api/auth/views.py
- open_prices/api/prices/views.py
- open_prices/api/proofs/views.py
- open_prices/api/serializers.py
- open_prices/api/urls.py
- open_prices/api/views.py
- open_prices/prices/models.py
Changes regarding the API : 
- move the docs endpoint out of the v1 namespace
- add serializers to login & session endpoints
- status endpoint : add a tag, and a response serializer
- fix Proof default queryset
- add `APPEND_SLASH = False` to avoid redirects, and `trailing_slash=False` in DRF setup
- fix decimal warning
```
- open_prices/api/auth/views.py: Warning [SessionView]: could not resolve authenticator <class 'open_prices.common.authentication.CustomAuthentication'>. There was no OpenApiAuthenticationExtension registered for that class. Try creating one by subclassing it. Ignoring for now.
- open_prices/api/prices/views.py: Warning [PriceViewSet]: could not resolve authenticator <class 'open_prices.common.authentication.CustomAuthentication'>. There was no …
```
> refactor(Django): improve API documentation

- open_prices/api/locations/serializers.py
- open_prices/api/locations/views.py
- open_prices/api/prices/serializers.py
- open_prices/api/prices/tests.py
- open_prices/api/prices/views.py
- open_prices/api/proofs/serializers.py
- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
- Price : add tests to check that the `proof_id` is passed
- Price & Proof : pass the FK ids in the readonly serializers
- source from `app_name` param : set a default value (`API`)
> refactor(Django): improve API serializers

- config/settings.py
- poetry.lock
- pyproject.toml
Setup [django-cors-headers](https://github.com/adamchainz/django-cors-headers) to allow API calls from anywhere (official frontend, or mobile, or external services)
> feat(Django): CORS configuration (allow all)

- config/settings.py
- open_prices/api/auth/views.py
- open_prices/api/locations/tests.py
- open_prices/api/pagination.py
- open_prices/api/prices/tests.py
- open_prices/api/products/tests.py
- open_prices/api/proofs/tests.py
- open_prices/api/urls.py
- open_prices/api/users/tests.py
- open_prices/common/openfoodfacts.py
- open_prices/locations/models.py
- open_prices/prices/models.py
- open_prices/prices/tests.py
- open_prices/products/models.py
- open_prices/products/tests.py
- open_prices/users/factories.py
Last fixes to match with the existing FastAPI backend
- rename paginator dict keys
- rename auth urls
- increment User.price_count on price create (and decrement on price delete) - #377
- manage product ArrayFields (instead of JsonField)
> fix(Django): last API fixes

- open_prices/api/pagination.py
- open_prices/api/prices/filters.py
- open_prices/api/prices/serializers.py
- open_prices/api/prices/tests.py
- open_prices/api/proofs/serializers.py
> fix(Django): extra API fixes round 2

- Makefile
- open_prices/users/admin.py
> chore(tests): run Django tests instead of FastAPI

- open_prices/api/prices/tests.py
- open_prices/api/prices/views.py
- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
On both Price GET & Proof GET, add [`select_related`](https://docs.djangoproject.com/en/5.1/ref/models/querysets/#select-related) to avoid N+1 queries
> perf(Django): Use select_related to avoid N+1 queries

- .github/workflows/container-deploy.yml
- Makefile
- docker-compose.yml
- nginx.conf
When static files change, we run automatically `make cp-static-files` in production.
> chore: fix static configuration

- open_prices/api/tests.py
- open_prices/api/views.py
Solves OFF probes that query `/api/status` with Basic Auth
> fix(Django): allow querying api/status with any auth

- open_prices/api/auth/views.py
- open_prices/api/locations/tests.py
- open_prices/api/locations/views.py
- open_prices/api/prices/tests.py
- open_prices/api/products/tests.py
- open_prices/api/products/views.py
- open_prices/api/proofs/tests.py
- open_prices/api/utils.py
|Endpoint|Expected|Done ?|
|--|---|---|
|GET Location by osm id & type|Should return a JSON-formatted 404 + improve message|yes|
|GET Product by code|Should return a JSON-formatted 404 + improve message|yes|
|Auth|If error, return "detail" instead of "error"|yes|
> fix(Django): improve some API returns

- open_prices/locations/models.py
- open_prices/locations/tests.py
- open_prices/products/models.py
- open_prices/products/tests.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
- open_prices/users/models.py
- open_prices/users/tests.py
For the models with a `price_count` field (Product, Location, Proof, User), we add a `update_price_count` helper.
Will be useful for afterwards
> refactor(stats): new model update_price_count() methods

- INSTALL.md
- README.md
- docs/README.md
Fix #431 
Please Have a Review
> docs(Django): Updated project setup instruction

- open_prices/prices/models.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
We sometimes have users wanting to change their proof location.
Basic (internal) method to allow this : 
- updates the proof location
- updates the proof's prices location
- updates the price_counts
> refactor(proofs): simple update_location() method

- open_prices/api/prices/filters.py
- open_prices/api/prices/tests.py
- open_prices/api/products/tests.py
New Price API filtering options (for product categories)
- by `labels_tags`
- by `origins_tags`
> feat(prices): add API filter by labels_tags & origins_tags

- open_prices/prices/models.py
- open_prices/prices/tests.py
First step to build stats : simple querysets on the `Price` model
- exclude_discounted
- calculate_min
- calculate_max
- calculate_avg
- calculate_stats (count, min, max, avg)
> feat(prices): new querysets to calculate min, max & average

- open_prices/products/models.py
- open_prices/products/tests.py
Following #452
New properties on the `Product` model
- product.price__min
- product.price__max
- product.price__avg
- product.price__stats
> feat(products): new properties to calculate price min, max & average

- open_prices/common/tasks.py
Add a daily CRON (during the night) to update the `TotalStats` model
> refactor(stats): New daily CRON to update TotalStats

- open_prices/api/proofs/serializers.py
- open_prices/api/proofs/views.py
The current documentation doesn't explicit the fact that a `file` field is needed
> fix(API): Proofs: improve API documentation for upload

- open_prices/common/tasks.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
See discussion in https://github.com/openfoodfacts/open-prices-frontend/issues/879
New Proof methods to "fix" their missing location/date/currency (if added from old versions of the mobile app)
Added a CRON that runs every night
> refactor(Proofs): Methods to update missing proof fields from prices

- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
Currently the API allows users to delete proofs even if the proof has prices.
(it would not delete prices, but set their proof_id to None)
To enforce data quality, and avoid mistakes, we restrict the deletion to only proofs without any prices.
What if the user linked the prices to a wrong proof for instance ? Will need to upload a new proof first, and the prices again to this new proof (maybe allow one day to update the price's proof, or update the proof image ?)
- https://github.com/openfoodfacts/open-prices/pull/197
> fix(Proofs): Deny users to delete a proof with prices

- open_prices/api/prices/serializers.py
- open_prices/api/prices/tests.py
- open_prices/prices/models.py
- open_prices/prices/tests.py
- open_prices/proofs/models.py
Update the `Price` model validation & API to allow users to pass a `location_id`
- if a OSM location, then the location_osm_id & location_osm_type are still mandatory and should match
- if a ONLINE location, then the location_osm_id & location_osm_type should be empty
> feat(Prices): Allow adding new prices with a location_id

- open_prices/api/proofs/tests.py
Currently the folder img/0001 keeps adding new images when running the tests (Proof API upload tests), but there is no mechanism to delete them.
"Hack" to fix this
> fix(Tests): Remove proof images on test tearDown

- open_prices/api/locations/tests.py
- open_prices/api/prices/tests.py
- open_prices/api/proofs/serializers.py
- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
- open_prices/locations/tests.py
- open_prices/prices/models.py
- open_prices/prices/tests.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
Similar to #527
Update the `Proof` model validation & API to allow users to pass a `location_id`
- if a OSM location, then the location_osm_id & location_osm_type are still mandatory and should match
- if a ONLINE location, then the location_osm_id & location_osm_type should be empty
> feat(Proofs): Allow adding new proofs with a location_id

- open_prices/api/prices/tests.py
- open_prices/api/prices/views.py
- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
- open_prices/api/utils.py
We already store the app_name.
The mobile also sends us the app_version. Useful to understand which version the users are currently using.
> refactor(API): store app_version in Price & Proof source field

- open_prices/prices/models.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
After updating a Proof, cascade the changes to the proof's prices
> feat(Proofs): on update, also update proof prices

- open_prices/api/proofs/tests.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
Following #538, allow updating Proof `location_osm_id` & `location_osm_type` fields
> feat(API): Allow updating Proof location fields

- open_prices/proofs/utils.py
> fix: add types to functions and improve docstring in proofs/utils.py

- nginx.conf
Otherwise, it can't be loaded from other website, ex: Label Studio instance
It was already tested (and hotfixed) in production.
> chore: add CORS headers to images

- .env
- .github/workflows/container-deploy.yml
- config/settings.py
- docker-compose.yml
- open_prices/api/proofs/views.py
- open_prices/proofs/tests.py
- open_prices/proofs/utils.py
> feat: run OCR extraction on every new image

- open_prices/api/proofs/views.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
- open_prices/proofs/utils.py
Following  #543
Some refactoring : 
- call the OCR async task in the model's post_save signal (instead of the API view)
- don't run the task when running the tests (locally or in the CI) : avoids calls to Google API
- rename run_ocr_task to fetch_and_save_ocr_data for clarification
--> similar to what we have currently with the Location & Product async tasks
> refactor(proofs): run OCR in post_save signal instead of create

- poetry.lock
- pyproject.toml
Lots of changes recently in the [openfoodfacts-python](https://github.com/openfoodfacts/openfoodfacts-python) package.
Update from v0.2.1 to v2.2.0
> chore: update dependency openfoodfacts-python

- open_prices/common/openfoodfacts.py
- open_prices/common/tasks.py
Thanks to recent changes in `openfoodfacts-server` & `openfoodfacts-python` (see #281 for details), we can now fetch 25k additional OFF products that are marked as obsolete in the OFF DB (by the producers).
Added to the daily sync
> feat(Sync): fetch OFF obsolete products (25k items)

- open_prices/api/locations/serializers.py
- open_prices/api/locations/tests.py
- open_prices/api/locations/views.py
- open_prices/api/proofs/views.py
- open_prices/locations/tests.py
Following #446
Users can create a Location via the API.
But if the location already exist, we prefer to return the existing object (with a 200), instead of an error.
> feat(API): on Location POST, return existing if duplicate

- open_prices/common/tests.py
- open_prices/common/utils.py
- open_prices/locations/constants.py
- open_prices/locations/models.py
- open_prices/locations/tests.py
Improve the Location model's `cleanup_url` method, to only keep the `website_url` domain
Example : 
- input : https://satoriz-albertville.bio/collections/epicerie-salee/products/re44090
- output : https://satoriz-albertville.bio
> refactor(Locations): keep only website_url domain

- open_prices/prices/models.py
- open_prices/prices/tests.py
We perform the translation to its canonical tag ID in the validation of the `Price` model.
This PR will allow https://github.com/openfoodfacts/smooth-app/issues/5553
I tested it locally, it works as expected!
Similar to #548
> feat: allow users to submit origin tags in their language

- open_prices/proofs/utils.py
Following #543 and #549.
In this script [openfoodfacts-server/blob/main/scripts/run_ocr.py](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/scripts/run_ocr.py) you also run 
```json
"features": [
{"type": "TEXT_DETECTION"},
{"type": "LOGO_DETECTION"},
{"type": "LABEL_DETECTION"},
{"type": "SAFE_SEARCH_DETECTION"},
{"type": "FACE_DETECTION"},
],
```
not only TEXT_DETECTION, this PR adds these features as well.
Documentation for available features: https://cloud.google.com/vision/docs/reference/rest/v1/Feature
> refactor(proofs): more features to OCR extraction

- open_prices/common/openstreetmap.py
- open_prices/locations/management/commands/set_location_osm_brand_and_version.py
Following #591
A script (management command) that gets the location history from the OSM API, and sets the corresponding brand & version (depending on the location's created timestamp).
We'll need to figure out in the future on how we UPDATE a location :sweat_smile:
> feat(Location): script to fill in OSM brand & version

- Makefile
- open_prices/api/proofs/serializers.py
- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
- open_prices/proofs/factories.py
- open_prices/proofs/tests.py
By doing so, the client can know all predictions related to the user proof.
> feat: return proof predictions in `GET /api/v1/proof` route

- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
Currently only logged in users could GET their own proofs.
With this PR we allow anyone (even anonymous users) to access proofs (GET requests).
POST, PATCH & DELETE requests still require authentication.
> refactor(API): allow anyone to access proof data

- open_prices/api/prices/views.py
- open_prices/api/proofs/serializers.py
- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
Following #601 
Only return proof predictions on the "retrieve" endpoint /api/v1/proofs/<proof_id> (not on the "list")
> refactor(API): only return proof.predictions in detail endpoint

- config/settings.py
- open_prices/api/proofs/tests.py
- open_prices/api/proofs/views.py
Changes to the proof `/upload` endpoint:
- remove the permission check
- set the owner to `openfoodfacts-contributors` if the user is not authenticated
> feat(API): Allow anonymous users to upload proofs

- open_prices/proofs/ml/image_classifier.py
- poetry.lock
- pyproject.toml
I moved ML related code for object detection and image classification to `openfoodfacts` library, in a new `ml` module.
This module is used here in Open Prices, and will be used in Robotoff as well.
> fix: use openfoodfacts.ml module for proof classification

- open_prices/proofs/tests.py
- open_prices/proofs/utils.py
Solves #615
When the proof image folder reached the limit of 1000, we created a new image dir and stored the image in it, but without the 0 padding. This directory was never used again.
That's why we had directories named `1`, `2`,... `10` in the image dir.
> fix: fix bug in directory selection for proof image

- .github/workflows/container-deploy.yml
- open_prices/products/tasks.py
- open_prices/products/tests.py
We didn't create a product when the product was missing.
Also:
- add unit tests to `process_update`
- use production redis to listen to update: as Open Prices uses production OFF as backend, it makes sense to use the same.
> fix: create a product if needed after a redis update event

- docker-compose.yml
The envvar was not passed to docker containers, resulting in sentry indicating "production" as environment irrespective of the real environment
> chore: pass ENVIRONMENT envvar to services

- open_prices/proofs/ml.py
- Ask gemini to also extract product_name
- Suggest that barcodes are EAN-13
- We could also add something like "Try to fix barcodes", but it doesn't seem to really help detection. Iinstead it tends to spit out wrong, but valid, barcodes. Which I believe would lead to more user mistakes during validation.
- https://github.com/openfoodfacts/open-prices-frontend/issues/1078
> feat(ProofMl): extract product_name and suggest ean-13 barcodes

- open_prices/api/proofs/views.py
- open_prices/proofs/ml.py
Gemini sometimes skips some images when prediction price tag labels, leading to mismatch between price tag and predictions.
We process here one price tag at a time, preventing this from happening.
> fix: process one image at a time with Gemini

- open_prices/proofs/management/commands/match_price_tags_with_existing_prices.py
Move the script into a reusable command
See https://github.com/openfoodfacts/open-prices/issues/637#issuecomment-2557890286
> feat(Price tags): script to match historical PriceTag with their prices

- open_prices/api/locations/tests.py
- open_prices/api/prices/tests.py
- open_prices/api/proofs/tests.py
- open_prices/api/utils.py
Following #533 we store the `app_name` & `app_version` query params in the Price/Proof/Location source field.
In this PR we now also store the `app_platform` (sent from mobile) and a `app_page` (soon to be sent from the web app).
Will need to run a script to fix/adapt the past sources once the frontend sends the `app_page` info (instead of hacking the `app_version` param)
> refactor(API): store query params app_platform & app_page in source field

- open_prices/proofs/management/commands/match_price_tags_with_existing_prices.py
- open_prices/proofs/utils.py
Carrefour barcodes are hard to detect.
We help the matching script for this specific case :)
I also moved the matching logic out of the management command and into `proofs/utils.py` 
|Image|predicted barcode (before)|predicted barcode (after)
|---|---|---|
|![image](https://github.com/user-attachments/assets/4999dc41-0c2b-421e-85b7-84e61a851f1c)|`182492/3119789831280/051`|`3119789831280`|
> refactor(Price tags): improve matching script: manage Carrefour barcodes

- open_prices/proofs/management/commands/match_price_tags_with_existing_prices.py
- open_prices/proofs/utils.py
Following #650 & #660
Add an extra step in the matching script, to matching existing PriceTags predictions on existing Prices only on the price value.
cc @TTalex
> refactor(Price tags): matching script: try to match on price only

- open_prices/locations/models.py
- open_prices/locations/tests.py
- open_prices/products/tests.py
- open_prices/stats/tests.py
- open_prices/users/models.py
- open_prices/users/tests.py
Following #609 
We need to adapt how some stats are calculated:
- User location count: do the aggregation on proofs, not on prices
- Location user count: do the aggregation on proofs, not on prices
Also simplified the User proof count calculation. And update the tests
> fix(Stats): fix User & Location stats after allowing any user to add prices on PRICE_TAG proofs

- open_prices/api/prices/filters.py
- open_prices/api/prices/tests.py
- open_prices/api/proofs/tests.py
- Allows for filtering using `product__categories_tags__contains` on price APIs
- Fixes #673
> feat(Prices): API: new filter on product category_tags

- open_prices/proofs/ml.py
When diving into our usage of ML, I realized that we run the `price_tag_detection` model even on non-Price tag proofs.
Nevertheless, we already had a check afterwards that would avoid creating the corresponding `PriceTag` objects for these kinds of proofs.
So moved up the check, and will cleanup the history once it is deployed
```
Proof.objects.count()
// 17485
ProofPrediction.objects.count()
// 34956
ProofPrediction.objects.exclude(proof__type="PRICE_TAG").count()
// 6292
Counter(ProofPrediction.objects.exclude(proof__type="PRICE_TAG").values_list("model_name", flat=True))
// {'price_proof_classification': 3152, 'price_tag_detection': 3140}
```
> fix(Proofs): Run price tag prediction only on PRICE_TAG proofs

- open_prices/prices/models.py
- open_prices/proofs/tests.py
> fix(Prices): on price delete, also update any related PriceTag status

- .github/workflows/container-deploy.yml
Following new settings in #705, and Redis live sync in #618
Disable the OFF product sync. Not needed anymore.
> refactor(Product sync): disable OFF daily sync (now that we have Redis live updates)

- open_prices/proofs/ml.py
- open_prices/proofs/tests.py
- Uses gemini to extract receipt content
- Stores it in the proof_predictions database
I did try to ask Gemini for way more information (see commented fields), but it tends to confuse it. Sometimes it replies with all fields, and sometimes it forgets to add everything, including price.
```python
class Item(typing.TypedDict):
product: Products
price: float
product_name: str
class Receipt(typing.TypedDict):
store_name: str
store_address: str
store_city_name: str
date: str
items: list[Item]
```
The shorter list seems to perform better.
Extraction of store name, address and date could be quite useful. However, in the current process, these are already specified by the user when the proof reaches the ml (also true for proof type prediction).
Since users currently manually mark the proof as a …
> feat(Proofs): ML: receipt content extraction

- open_prices/api/prices/filters.py
- open_prices/api/prices/tests.py
Allow filtering prices by `proof__type` (1 or multiple types allowed)
```
?proof__type=PRICE_TAG  # community
?proof__type=RECEIPT&proof__type=GDPR_REQUEST  # consumption
```
> feat(Prices): API: new filter on proof type

- open_prices/api/pagination.py
- Fix discrepancy between Api Docs and our custom paginitation keywords.
Example with user lists, but it applies to all paginated results (prices, proofs ..)
| Before | After |
| ------ | ------ |
|![paginationbefore](https://github.com/user-attachments/assets/80ef9346-2f1c-47e1-959c-3f1aba8075aa) | ![paginationfix](https://github.com/user-attachments/assets/ff45a983-ea85-40df-997c-38f1d1e7d082)|
- Fixes #742
> docs(API): custom paginated response schema

- config/settings.py
- open_prices/api/pagination.py
- open_prices/api/prices/tests.py
Our API was wrongly configured, we didn't have a max size set. 
I was seeing calls with `?size=700000` (:eyes:) making the server crash...
- default to size = 10
- max size = 100
> refactor(API): set default size to 10. and limit max size to 100

- open_prices/api/proofs/filters.py
- open_prices/api/proofs/tests.py
Similar to #741
Allow filtering by multiple values of the `type` field
> refactor(Proofs): API: allow multiple filters on `type`

- open_prices/api/auth/views.py
- OpenAPI docs were showing json as a possible content-type option for `POST /api/v1/auth`, which was incorrect
- Fixes #544
- Did a quick check to make sure this doesn't affect the dart app https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/src/open_prices_api_client.dart
- It shouldn't be an issue, the app is correctly using `Content-Type: application/x-www-form-urlencoded` by default
> refactor(Auth): Drop invalid json parser from post api

- open_prices/prices/models.py
- open_prices/prices/tests.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
- open_prices/stats/tests.py
- open_prices/users/tests.py
We introduced type groups in #726.
But with the new `Proof.owner_consumption` field (see #750), we need to manage the case where some RECEIPTs go in the community stats (instead of consumption)
> refactor(Proofs): take owner_consumption into account to differentiate community & consumption

- open_prices/api/prices/filters.py
- open_prices/api/prices/tests.py
Following #773 & #775, and similar to #776
allow filtering prices by kind: COMMUNITY or CONSUMPTION
> feat(Prices): API: new filter on `kind`

- open_prices/proofs/management/commands/match_price_tags_with_existing_prices.py
- open_prices/proofs/tests.py
- open_prices/proofs/utils.py
Following #650
- fix a typo that probably didn't allow to match any TYPE_CATEGORY prices
- add tests (following tests on the price matching function: https://github.com/openfoodfacts/open-prices/commit/2f55f534e7c4e94278ea61dc25a944c88c7107f0)
> refactor(Price tags): matching script: fix script for category_tag. add tests

- open_prices/api/prices/filters.py
- open_prices/api/prices/tests.py
This PR allows to do the following (complex) API query:
```
?product__categories_tags__overlap=en:breakfasts,en:rices
```
> refactor(API): Prices: allow multiple (overlap) filter on product categories_tags field

- open_prices/api/prices/filters.py
- open_prices/api/prices/tests.py
Following #807
We allow filtering on the new `Price.tags` field
> feat(Prices): API: new filter by tags (contains)

- open_prices/prices/models.py
- open_prices/prices/tasks.py
- open_prices/prices/tests.py
Following #807 (new `Price.tags` field)
New signal on price create, to set any ongoing challenge tag
> feat(Challenges): set the price tag on price create (if the price belongs to an ongoing challenge)

- open_prices/challenges/tests.py
- open_prices/prices/tests.py
- open_prices/proofs/models.py
- open_prices/proofs/tests.py
Following the addition of `Proof.tags` in #817 
- new Proof queryset `in_challenge` (with tests) (similar to #808)
- new Proof property `in_challenge` (with tests) (similar to #810)
> refactor(Challenges): new Proof queryset & property to filter on the ones part of a challenge

- open_prices/api/proofs/filters.py
- open_prices/api/proofs/tests.py
Following #817, and similar to #813
We allow filtering on the new Proof.tags field
> feat(Proofs): API: new filter by tags (contains)

- open_prices/prices/tasks.py
- open_prices/prices/tests.py
- open_prices/proofs/tests.py
Following #814 (new `Proof.tags` field)
Following #811, but this time for proofs
We use the price create signal: if the price is part of the challenge, then the proof is as well
> refactor(Challenges): set the price's proof tag on price create (if the price belongs to an ongoing challenge)

- open_prices/proofs/management/commands/set_price_product_name_from_proof_predictions.py
Following #650 & #788
We have scripts to match existing Prices with their PriceTag & ReceiptItem counterpart.
But sending the predicted `product_name` is also a useful info.
> feat(Prices): script to set missing product_name from PriceTag & ReceiptItem

- open_prices/common/tasks.py
Thanks to #810 & #819
Run a daily (nightly) task to set the challenge tag on any forgotten price & proof (for instance if the price's product category_tags have changed).
> feat(Challenges): new task to set Price & Proof tag every night

- open_prices/proofs/models.py
- open_prices/proofs/tests.py
Following #838
We use a signal on `PriceTagPrediction` creation, and update the `PriceTag.tags` field depending on rules defined in the previous PR
> feat(Price Tag): predictions: set price_tag tags on prediction creation

- open_prices/prices/models.py
- open_prices/prices/tests.py
The normalization was effective for `category_tag`, `origins_tags` but not for `labels_tags`.
Fixes #855.
> fix: normalize `price.label_tags` taxonomized values

- poetry.lock
We have many connection errors to Google servers, which may be due to an outdated `certifi` version.
> fix: upgrade certifi version

- open_prices/prices/management/commands/remove_duplicates.py
Remove duplicated prices, only for prices associated with proof of type
PRICE_TAG.
This command currently only removes duplicated prices coming from the
same proof, duplicated proofs are not handled yet.
We first create a CTE (temporary Common Table Expression) to find all
duplicate prices. Prices are considered as duplicated if their have the
same (`product_code`/`category_tag`, `price`, `proof_id`).
We then loop on each group of duplicate prices, keeping the first one
(the one with the lowest ID) and removing the others. If any of the
duplicate prices is linked to a price tag, we update the price tag to
point to the first price instead of the removed one.
> chore: add a script to detect duplicated prices

- open_prices/proofs/management/commands/remove_duplicate_proofs.py
Remove duplicated proofs, based on the provided filters.
This script removes all prices and proofs (excluding the reference proof and associated prices) that have the same owner, date, and location ID as the reference proof. It is useful to clean up the database from duplicate proofs that may have been created by mistake.
> chore: add script to remove duplicate proofs

- open_prices/proofs/models.py
- open_prices/proofs/tests.py
This broke after we introduced new schema for Gemini output
> fix: fix `get_predicted_price` method

- open_prices/proofs/management/commands/remove_duplicate_proofs.py
Related issue: #514
This option is activated by default, making the script much safer.
> fix: check raw image MD5 in script to delete duplicate proofs

- Makefile
most of the time, we don't provide any arguments to it.
> chore: remove required arguments for makemigrations

- open_prices/common/authentication.py
- open_prices/common/tests.py
In #969 we did some refactoring on how we read the Bearer token, and involuntarily introduced a case-sensitive check on the word "Bearer".
But the specs allow for flexibility : https://auth0.com/blog/the-bearer-token-case/
This PR fixes this.
Follows a discussion in https://github.com/openfoodfacts/openfoodfacts-dart/issues/1128
> fix(API): Make the Bearer token prefix case-insensitive

- open_prices/proofs/management/commands/compute_missing_image_hash.py
- open_prices/proofs/utils.py
For proofs for which this field is null.
Linked to #514
Following the addition of the field in #964
> chore(Proofs): add a CLI command to compute the MD5 hash of image files

- open_prices/proofs/management/commands/remove_duplicate_proofs.py
It now uses the new `image_md5_hash` field to find all group of proofs that have the same, date, owner, location_id and image_md5_hash.
> chore: update the remove_duplicate_proofs.py script

- open_prices/prices/migrations/0012_price_labels_tags_temp_price_origins_tags_temp.py
Following #998
Note : probably should merge as is, but this fixed my setup
Some prices have non-array values stored in `origins_tags` & `labels_tags`
> fix(Migration): fix price migration 0012 (ArrayField)

- open_prices/common/db_func.py
- open_prices/products/migrations/0007_add_fuzzystrmatch_extension.py
- open_prices/products/models.py
- open_prices/products/tests.py
- open_prices/proofs/ml.py
Using levenshtein distance, we search for the similar barcodes (with a distance <= 3) so that we can suggest products based on the (wrongly) extracted barcode. Luckily, we can leverage a PostgreSQL native extension (https://www.postgresql.org/docs/current/fuzzystrmatch.html#FUZZYSTRMATCH-LEVENSHTEIN) to perform efficiently fuzzy search on barcode, using the `products` table. 
We save the result in `data.similar_barcodes` field of the `PriceTagPrediction`:
`[{"distance": 2, "barcode": "5252525"}]`
`distance` is the levenhstein distance with the extracted barcode and `barcode` is the match.
We don't include in the list the original barcode (distance=0). There is at most 10 items in this list.
The front-end needs to be updated to leverage this new field.
I performed a few tests (~15) using …
> feat: implement a barcode similarity search feature for price tags

- open_prices/api/prices/views.py
Similar to #947 & #1014
Relieve a bit the load on the API/DB by replacing the default Price API sort from `created` to `id`
Long term solution: add indexes (#949)
> fix(API): Prices: order by ID by default instead of created

- config/settings.py
- open_prices/api/products/tests.py
- open_prices/api/products/views.py
- open_prices/common/openfoodfacts.py
- Backend part of PR https://github.com/openfoodfacts/open-prices-frontend/pull/1685 allowing Product Opener products addition from Open Prices
- Uses two new settings: OFF_DEFAULT_USER & OFF_DEFAULT_PASSWORD, that should contain username and password of a "default" Open Prices user
- The PR also uses two recently-added filters:
- `source_isnull` on products, to find products added to the prices' database, but not existing on any Product Opener database : https://github.com/openfoodfacts/open-prices/issues/1030
- `price_id` on proofs, in order to fetch the proof containing a specific price : https://github.com/openfoodfacts/open-prices/issues/1033
> feat(Products): New API endpoints to update/add Product Opener products and images

- config/settings.py
- open_prices/common/openfoodfacts.py
In https://github.com/openfoodfacts/open-prices/commit/89c68994ea2492355e12102a9f3783f9224fa136 we had created a new OFF_ENVIRONMENT setting to allow switching from .net to .org
But there is already a ENVIRONMENT env var that is set during deploy. reuse it
> fix(settings): rename OFF_ENVIRONEMENT to ENVIRONMENT
